---
title: "Bellabeat Case Study"
author: "Robert Castillo"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
options(width = 90, xtable.comment = FALSE)
```

```{r}
if( !dir.exists("_assets")){
  dir.create("_assets")
}
```

```{r}
# Install necessary packages
install.packages('tidyverse')
install.packages('janitor')
install.packages('lubridate')
install.packages('skimr')
install.packages('xtable')
```

```{r}
# Load libraries
library(tidyverse)
library(janitor)
library(lubridate)
library(skimr)
library(xtable)
```

```{r}
# Load in the datasets
daily_activity <- read.csv("dailyActivity_merged.csv")
sleep_day <- read.csv("sleepDay_merged.csv")
weight_info <- read.csv("weightLogInfo_merged.csv")
```

```{r}
# Check the structure for any glaring format issues
str(daily_activity)
str(sleep_day)
str(weight_info)
```

```{r}
# Clean column names
daily_activity <- clean_names(daily_activity)
sleep_day <- clean_names(sleep_day)
weight_info <- clean_names(weight_info)
```

```{r}
# Remove unused columns
daily_activity_keep <- c('id','activity_date','total_steps','total_distance',
                         'very_active_minutes','fairly_active_minutes', 'lightly_active_minutes',
                         'sedentary_minutes', 'calories')
sleep_day_keep <- c('id', 'sleep_day', 'total_minutes_asleep')
weight_info_keep <- c('id', 'date', 'weight_pounds')

daily_activity <- daily_activity %>% select(all_of(daily_activity_keep))
sleep_day <- sleep_day %>% select(all_of(sleep_day_keep))
weight_info <- weight_info %>% select(all_of(weight_info_keep))
```

```{r}
# Change date columns to date format
daily_activity$activity_date <- as.Date(daily_activity$activity_date, format('%m/%d/%Y'))

sleep_day$sleep_day <- parse_date_time(sleep_day$sleep_day, '%m/%d/%Y %I:%M:%S %p')
sleep_day$sleep_day <- as.Date(as.character(sleep_day$sleep_day), format('%Y-%m-%d'))

# weight log requires a little more work
weight_info$date <- parse_date_time(weight_info$date, '%m/%d/%Y %I:%M:%S %p')
weight_info$date <- format(as.POSIXct(weight_info$date, format = '%Y%m%d %H:%M:%S'),
                           format = '%Y-%m-%d')
weight_info$date <- as.Date(weight_info$date, format('%Y-%m-%d'))
```

```{r}
# Change column names for simplicity
colnames(daily_activity)[colnames(daily_activity) == 'activity_date'] <- 'date'
colnames(sleep_day)[colnames(sleep_day) == 'sleep_day'] <- 'date'
```

```{r}
# Merge dataframes
activity_sleep_merge <- merge(daily_activity, sleep_day, by = c('id', 'date'), all = TRUE)
activity_weight_merge <- merge(daily_activity, weight_info, by = c('id', 'date'), all = TRUE)
sleep_weight_merge <- merge(sleep_day, weight_info, by = c('id', 'date'), all = TRUE)
```

```{r}
# Remove NAs
activity_sleep_merge <- activity_sleep_merge %>% drop_na()
activity_weight_merge <- activity_weight_merge %>% drop_na()
sleep_weight_merge <- sleep_weight_merge %>% drop_na()
```

```{r}
# Add Weekday to activity and sleep merged data and turn it into a factor
activity_sleep_merge <- activity_sleep_merge %>% mutate(weekday = weekdays(date))

activity_sleep_merge$weekday <- factor(activity_sleep_merge$weekday,
                                       levels = c('Monday','Tuesday','Wednesday', 'Thursday',
                                                  'Friday', 'Saturday', 'Sunday'))
```

```{r}
# Create Pivot Table for summary plots
activity_sleep_pivot <- activity_sleep_merge %>%
  group_by(weekday) %>%
  summarize(mean_sleep_minutes = mean(total_minutes_asleep),
            mean_steps = mean(total_steps),
            mean_distance = mean(total_distance),
            mean_sed_minutes = mean(sedentary_minutes),
            mean_la_minutes = mean(lightly_active_minutes),
            mean_fa_minutes = mean(fairly_active_minutes),
            mean_va_minutes = mean(very_active_minutes))
```


```{r}
# Create plot of avg sleep minutes per Weekday
p <- ggplot(data = activity_sleep_pivot, aes(x = weekday, y = mean_sleep_minutes)) + 
  geom_bar(stat = 'identity', fill = 'blue') +
  labs(title = 'Average Minutes of Sleep by Weekday')+
  ylab('Avg. Minutes of Sleep') +
  xlab('Weekday')

png(file.path(getwd(),"_assets",
              "Sleep_Minutes_Weekday.png")
    )
print(p)

dev.off()
```

```{r}
# Create plot of avg steps per Weekday
p <- ggplot(data = activity_sleep_pivot, aes(x = weekday, y = mean_steps)) + 
  geom_bar(stat = 'identity', fill = 'blue') +
  labs(title = 'Average Steps by Weekday')+
  ylab('Avg. Steps') +
  xlab('Weekday')

png(file.path(getwd(),"_assets",
              "Steps_Weekday.png")
    )
print(p)

dev.off()
```

```{r}
# Create plot of avg distance per Weekday
p <- ggplot(data = activity_sleep_pivot, aes(x = weekday, y = mean_distance)) + 
  geom_bar(stat = 'identity', fill = 'blue') +
  labs(title = 'Average Distance Traveled by Weekday')+
  ylab('Avg. Distance (km)') +
  xlab('Weekday')

png(file.path(getwd(),"_assets",
              "Distance_Weekday.png")
    )
print(p)

dev.off()
```

```{r}
# Create plot of avg sedentary minutes per Weekday
p <- ggplot(data = activity_sleep_pivot, aes(x = weekday, y = mean_sed_minutes)) + 
  geom_bar(stat = 'identity', fill = 'blue') +
  labs(title = 'Average Sedentary Minutes by Weekday')+
  ylab('Avg. Sedentary Minutes') +
  xlab('Weekday')

png(file.path(getwd(),"_assets",
              "Sedentary_Weekday.png")
    )
print(p)

dev.off()
```

```{r}
# Create plot of avg lightly active minutes per Weekday
p <- ggplot(data = activity_sleep_pivot, aes(x = weekday, y = mean_la_minutes)) + 
  geom_bar(stat = 'identity', fill = 'blue') +
  labs(title = 'Average Lightly Active Minutes by Weekday')+
  ylab('Avg. Lightly Active Minutes') +
  xlab('Weekday')

png(file.path(getwd(),"_assets",
              "Lightly_Weekday.png")
    )
print(p)

dev.off()
```

```{r}
# Create plot of avg fairly active minutes per Weekday
p <- ggplot(data = activity_sleep_pivot, aes(x = weekday, y = mean_fa_minutes)) + 
  geom_bar(stat = 'identity', fill = 'blue') +
  labs(title = 'Average Fairly Active Minutes by Weekday')+
  ylab('Avg. Fairly Active Minutes') +
  xlab('Weekday')

png(file.path(getwd(),"_assets",
              "Fairly_Weekday.png")
    )
print(p)

dev.off()
```

```{r}
# Create plot of avg very active minutes per Weekday
p <- ggplot(data = activity_sleep_pivot, aes(x = weekday, y = mean_va_minutes)) + 
  geom_bar(stat = 'identity', fill = 'blue') +
  labs(title = 'Average Very Active Minutes by Weekday')+
  ylab('Avg. Very Active Minutes') +
  xlab('Weekday')

png(file.path(getwd(),"_assets",
              "Very_Weekday.png")
    )
print(p)

dev.off()
```

```{r}
# Create activity scores to help determine individual daily activity levels 
activity_sleep_merge$very_active_score <-
  activity_sleep_merge$very_active_minutes/mean(activity_sleep_merge$very_active_minutes)

activity_sleep_merge$fairly_active_score <-
  activity_sleep_merge$fairly_active_minutes/mean(activity_sleep_merge$fairly_active_minutes)

activity_sleep_merge$lightly_active_score <-
  activity_sleep_merge$lightly_active_minutes/mean(activity_sleep_merge$lightly_active_minutes)

activity_sleep_merge$sedentary_score <-
  activity_sleep_merge$sedentary_minutes/mean(activity_sleep_merge$sedentary_minutes)
         
```



```{r}
# Create the activity level on a row by row basis
activity_level <- c()

for (i in 1:nrow(activity_sleep_merge)) {
  if(max(activity_sleep_merge$very_active_score[i],
         activity_sleep_merge$fairly_active_score[i],
         activity_sleep_merge$lightly_active_score[i],
         activity_sleep_merge$sedentary_score[i]) == activity_sleep_merge$sedentary_score[i]){
    activity_level[i] <- "Sedentary"
  } else if(max(activity_sleep_merge$very_active_score[i],
         activity_sleep_merge$fairly_active_score[i],
         activity_sleep_merge$lightly_active_score[i],
         activity_sleep_merge$sedentary_score[i]) ==
         activity_sleep_merge$lightly_active_score[i]){
    activity_level[i] <- "Lightly Active"
  } else if(max(activity_sleep_merge$very_active_score[i],
         activity_sleep_merge$fairly_active_score[i],
         activity_sleep_merge$lightly_active_score[i],
         activity_sleep_merge$sedentary_score[i]) ==
         activity_sleep_merge$fairly_active_score[i]){
    activity_level[i] <- "Fairly Active"
  } else if(max(activity_sleep_merge$very_active_score[i],
         activity_sleep_merge$fairly_active_score[i],
         activity_sleep_merge$lightly_active_score[i],
         activity_sleep_merge$sedentary_score[i]) ==
         activity_sleep_merge$very_active_score[i]){
    activity_level[i] <- "Very Active"
  }
}
```

```{r}
# Add activity level into the dataframe and turn it into a factor
activity_sleep_merge$activity_level <- activity_level

activity_sleep_merge$activity_level <- factor(activity_sleep_merge$activity_level,
                                       levels = c('Sedentary','Lightly Active',
                                                  'Fairly Active', 'Very Active'))

# Drop the score columns
activity_sleep_merge <- activity_sleep_merge %>% select(-c(sedentary_score,
                                                           lightly_active_score,
                                                           fairly_active_score,
                                                           very_active_score))
```


```{r}
# Create boxplots of calories burned for each activity level
p <- ggplot(data = activity_sleep_merge, aes(x = activity_level, y = calories,
                                        fill = activity_level)) +
  geom_boxplot() +
  theme(legend.position = 'none') +
  labs(title = 'Calories Burned by Activity Level') +
  ylab('Calories') +
  xlab('Activity Level')

png(file.path(getwd(),"_assets",
              "Calories_Activity_Level.png")
    )
print(p)

dev.off()
```


```{r}
# Create scatterplot for total steps and sleep minutes
p <- ggplot(data = activity_sleep_merge, aes(x = total_steps, y = total_minutes_asleep)) +
  geom_point(color = 'blue') +
  geom_smooth(method = lm) +
  labs(title = 'Relationship between Total Steps and Total Minutes Asleep')+
  ylab('Total Minutes Asleep') +
  xlab('Total Steps')

png(file.path(getwd(),"_assets",
              "Steps_Sleep.png")
    )
print(p)

dev.off()
```

```{r}
# Correlation between total steps and sleep minutes
cor(activity_sleep_merge$total_steps, activity_sleep_merge$total_minutes_asleep)
```


```{r}
# Create scatterplot for total distance and sleep minutes
p <- ggplot(data = activity_sleep_merge, aes(x = total_distance, y = total_minutes_asleep)) +
  geom_point(color = 'blue') +
  geom_smooth(method = lm) +
  labs(title = 'Relationship between Total Distance and Total Minutes Asleep')+
  ylab('Total Minutes Asleep') +
  xlab('Total Distance (km)')

png(file.path(getwd(),"_assets",
              "Distance_Sleep.png")
    )
print(p)

dev.off()
```

```{r}
# Correlation between total distance and sleep minutes
cor(activity_sleep_merge$total_distance, activity_sleep_merge$total_minutes_asleep)
```


```{r}
# Create scatterplot for very active minutes and sleep minutes
p <- ggplot(data = activity_sleep_merge, aes(x = very_active_minutes, y = total_minutes_asleep)) +
  geom_point(color = 'blue') +
  geom_smooth(method = lm) +
  labs(title = 'Relationship between Very Active Minutes and Total Minutes Asleep')+
  ylab('Total Minutes Asleep') +
  xlab('Very Active Minutes')

png(file.path(getwd(),"_assets",
              "Very_Sleep.png")
    )
print(p)

dev.off()
```

```{r}
# Correlation between very active minutes and sleep minutes
cor(activity_sleep_merge$very_active_minutes, activity_sleep_merge$total_minutes_asleep)
```


```{r}
# Create scatterplot for fairly active minutes and sleep minutes
p <- ggplot(data = activity_sleep_merge, aes(x = fairly_active_minutes, y = total_minutes_asleep)) +
  geom_point(color = 'blue') +
  geom_smooth(method = lm) +
  labs(title = 'Relationship between Fairly Active Minutes and Total Minutes Asleep')+
  ylab('Total Minutes Asleep') +
  xlab('Fairly Active Minutes')

png(file.path(getwd(),"_assets",
              "Fairly_Sleep.png")
    )
print(p)

dev.off()
```

```{r}
# Correlation between fairly active minutes and sleep minutes
cor(activity_sleep_merge$fairly_active_minutes, activity_sleep_merge$total_minutes_asleep)
```


```{r}
# Create scatterplot for lightly active minutes and sleep minutes
p <- ggplot(data = activity_sleep_merge, aes(x = lightly_active_minutes, y = total_minutes_asleep)) +
  geom_point(color = 'blue') +
  geom_smooth(method = lm) +
  labs(title = 'Relationship between Lightly Active Minutes and Total Minutes Asleep')+
  ylab('Total Minutes Asleep') +
  xlab('Lightly Active Minutes')

png(file.path(getwd(),"_assets",
              "Lightly_Sleep.png")
    )
print(p)

dev.off()
```

```{r}
# Correlation between lightly active minutes and sleep minutes
cor(activity_sleep_merge$lightly_active_minutes, activity_sleep_merge$total_minutes_asleep)
```


```{r}
# Create scatterplot for sedentary minutes and sleep minutes
p <- ggplot(data = activity_sleep_merge, aes(x = sedentary_minutes, y = total_minutes_asleep)) +
  geom_point(color = 'blue') +
  geom_smooth(method = lm) +
  labs(title = 'Relationship between Sedentary Minutes and Total Minutes Asleep')+
  ylab('Total Minutes Asleep') +
  xlab('Sedentary Minutes')

png(file.path(getwd(),"_assets",
              "Sedentary_Sleep.png")
    )
print(p)

dev.off()
```

```{r}
# Correlation between sedentary minutes and sleep minutes
cor(activity_sleep_merge$sedentary_minutes, activity_sleep_merge$total_minutes_asleep)
```

```{r}
# Create scatterplot for total steps and weight (pounds)
p <- ggplot(data = activity_weight_merge, aes(x = total_steps, y = weight_pounds)) +
  geom_point(color = 'blue') +
  geom_smooth(method = lm) +
  labs(title = 'Relationship between Total Steps and Weight')+
  ylab('Weight (lbs)') +
  xlab('Total Steps')

png(file.path(getwd(),"_assets",
              "Steps_Weight.png")
    )
print(p)

dev.off()
```

```{r}
# Correlation between total steps and weight (pounds)
cor(activity_weight_merge$total_steps, activity_weight_merge$weight_pounds)
```


```{r}
# Create scatterplot for total distance and weight (pounds)
p <- ggplot(data = activity_weight_merge, aes(x = total_distance, y = weight_pounds)) +
  geom_point(color = 'blue') +
  geom_smooth(method = lm) +
  labs(title = 'Relationship between Total Distance and Weight')+
  ylab('Weight (lbs)') +
  xlab('Total Distance (km)')

png(file.path(getwd(),"_assets",
              "Distance_Weight.png")
    )
print(p)

dev.off()
```

```{r}
# Correlation between total distance and weight (pounds)
cor(activity_weight_merge$total_distance, activity_weight_merge$weight_pounds)
```


```{r}
# Create scatterplot for very active minutes and weight (pounds)
p <- ggplot(data = activity_weight_merge, aes(x = very_active_minutes, y = weight_pounds)) +
  geom_point(color = 'blue') +
  geom_smooth(method = lm) +
  labs(title = 'Relationship between Very Active Minutes and Weight')+
  ylab('Weight (lbs)') +
  xlab('Very Active Minutes')

png(file.path(getwd(),"_assets",
              "Very_Weight.png")
    )
print(p)

dev.off()
```

```{r}
# Correlation between very active minutes and weight (pounds)
cor(activity_weight_merge$very_active_minutes, activity_weight_merge$weight_pounds)
```


```{r}
# Create scatterplot for fairly active minutes and weight (pounds)
p <- ggplot(data = activity_weight_merge, aes(x = fairly_active_minutes, y = weight_pounds)) +
  geom_point(color = 'blue') +
  geom_smooth(method = lm) +
  labs(title = 'Relationship between Fairly Active Minutes and Weight')+
  ylab('Weight (lbs)') +
  xlab('Fairly Active Minutes')

png(file.path(getwd(),"_assets",
              "Fairly_Weight.png")
    )
print(p)

dev.off()
```

```{r}
# Correlation between fairly active minutes and weight (pounds)
cor(activity_weight_merge$fairly_active_minutes, activity_weight_merge$weight_pounds)
```


```{r}
# Create scatterplot for lightly active minutes and weight (pounds)
p <- ggplot(data = activity_weight_merge,
       aes(x = lightly_active_minutes, y = weight_pounds)) +
  geom_point(color = 'blue') +
  geom_smooth(method = lm) +
  labs(title = 'Relationship between Lightly Active Minutes and Weight')+
  ylab('Weight (lbs)') +
  xlab('Lightly Active Minutes')

png(file.path(getwd(),"_assets",
              "Lightly_Weight.png")
    )
print(p)

dev.off()
```

```{r}
# Correlation between lightly active minutes and weight (pounds)
cor(activity_weight_merge$lightly_active_minutes, activity_weight_merge$weight_pounds)
```


```{r}
# Create scatterplot for sedentary minutes and weight (pounds)
p <- ggplot(data = activity_weight_merge, aes(x = sedentary_minutes, y = weight_pounds)) +
  geom_point(color = 'blue') +
  geom_smooth(method = lm) +
  labs(title = 'Relationship between Sedentary Minutes and Weight')+
  ylab('Weight (lbs)') +
  xlab('Sedentary Minutes')

png(file.path(getwd(),"_assets",
              "Sedentary_Weight.png")
    )
print(p)

dev.off()
```

```{r}
# Correlation between sedentary minutes and weight (pounds)
cor(activity_weight_merge$sedentary_minutes, activity_weight_merge$weight_pounds)
```



```{r}
# Create scatterplot for total steps and calories
p <- ggplot(data = activity_sleep_merge, aes(x = total_steps, y = calories)) +
  geom_point(color = 'blue') +
  geom_smooth(method = lm) +
  labs(title = 'Relationship between Total Steps and Calories')+
  ylab('Calories') +
  xlab('Total Steps')

png(file.path(getwd(),"_assets",
              "Steps_Calories.png")
    )
print(p)

dev.off()
```

```{r}
# Correlation between total steps and calories
cor(activity_sleep_merge$total_steps, activity_sleep_merge$calories)
```


```{r}
# Create scatterplot for total distance and calories
p <- ggplot(data = activity_sleep_merge, aes(x = total_distance, y = calories)) +
  geom_point(color = 'blue') +
  geom_smooth(method = lm) +
  labs(title = 'Relationship between Total Distance and Calories')+
  ylab('Calories') +
  xlab('Total Distance (km)')

png(file.path(getwd(),"_assets",
              "Distance_Calories.png")
    )
print(p)

dev.off()
```

```{r}
# Correlation between total distance and calories
cor(activity_sleep_merge$total_distance, activity_sleep_merge$calories)
```


```{r}
# Create scatterplot for very active minutes and calories
p <- ggplot(data = activity_sleep_merge, aes(x = very_active_minutes, y = calories)) +
  geom_point(color = 'blue') +
  geom_smooth(method = lm) +
  labs(title = 'Relationship between Very Active Minutes and Calories')+
  ylab('Calories') +
  xlab('Very Active Minutes')

png(file.path(getwd(),"_assets",
              "Very_Calories.png")
    )
print(p)

dev.off()
```

```{r}
# Correlation between very active minutes and calories
cor(activity_sleep_merge$very_active_minutes, activity_sleep_merge$calories)
```


```{r}
# Create scatterplot for fairly active minutes and calories
p <- ggplot(data = activity_sleep_merge, aes(x = fairly_active_minutes, y = calories)) +
  geom_point(color = 'blue') +
  geom_smooth(method = lm) +
  labs(title = 'Relationship between Fairly Active Minutes and Calories')+
  ylab('Calories') +
  xlab('Fairly Active Minutes')

png(file.path(getwd(),"_assets",
              "Fairly_Calories.png")
    )
print(p)

dev.off()
```

```{r}
# Correlation between fairly active minutes and calories
cor(activity_sleep_merge$fairly_active_minutes, activity_sleep_merge$calories)
```


```{r}
# Create scatterplot for lightly active minutes and calories
p <- ggplot(data = activity_sleep_merge, aes(x = lightly_active_minutes, y = calories)) +
  geom_point(color = 'blue') +
  geom_smooth(method = lm) +
  labs(title = 'Relationship between Lightly Active Minutes and Calories')+
  ylab('Calories') +
  xlab('Lightly Active Minutes')

png(file.path(getwd(),"_assets",
              "Lightly_Calories.png")
    )
print(p)

dev.off()
```

```{r}
# Correlation between lightly active minutes and calories
cor(activity_sleep_merge$lightly_active_minutes, activity_sleep_merge$calories)
```


```{r}
# Create scatterplot for sedentary minutes and calories
p <- ggplot(data = activity_sleep_merge, aes(x = sedentary_minutes, y = calories)) +
  geom_point(color = 'blue') +
  geom_smooth(method = lm) +
  labs(title = 'Relationship between Sedentary Minutes and Calories')+
  ylab('Calories') +
  xlab('Sedentary Minutes')

png(file.path(getwd(),"_assets",
              "Sedentary_Calories.png")
    )
print(p)

dev.off()
```

```{r}
# Correlation between sedentary minutes and calories
cor(activity_sleep_merge$sedentary_minutes, activity_sleep_merge$calories)
```

```{r}
# Save datasets for a Tableau Dashboard
write.csv(activity_sleep_merge, file = "Activity_Sleep_Merge.csv")
write.csv(activity_weight_merge, file = "Activity_Weight_Merge.csv")
```

```{r}
# Get summary info
summary(activity_sleep_merge)

act_sleep_table <- xtable(summary(activity_sleep_merge),
                          caption = 'Activity_Sleep_Summary',
                          label = 'Act_Sleep_Sum')
act_sleep_sum <- print(act_sleep_table, include.rownames = FALSE, table.placement = 'H')

writeLines(act_sleep_sum, file.path('_assets', 'Activity_Sleep_Summary.tex'))
```

```{r}
summary(activity_weight_merge)

act_weight_table <- xtable(summary(activity_weight_merge),
                          caption = 'Activity_Weight_Summary',
                          label = 'Act_Weight_Sum')
act_weight_sum <- print(act_weight_table, include.rownames = FALSE, table.placement = 'H')

writeLines(act_weight_sum, file.path('_assets', 'Activity_Weight_Summary.tex'))
```

